project:
  type: website
  output-dir: pdfs
  render:
    - "*.qmd"
    - "!old/"

execute:
  freeze: auto

format:
  beamer:
    theme: Pittsburgh
    colortheme: default
    fonttheme: default
    pdf-engine: lualatex
    include-in-header:
      - file: header.tex
