---
title: "Prostate cancer"
format: html
---

# EDA

```{r}
library(tidyverse)
```

```{r}
prostate <- read_delim("prostatecancer.dat", delim = " & ") |>
  mutate(Nodes = as.factor(Nodes))
glimpse(prostate)
```

```{r}
ggplot(prostate, aes(x = Acid, y = Nodes, color = Nodes)) +
  geom_jitter(height = 0.10)
```


```{r}
ggplot(prostate, aes(x = Acid, y = Nodes, fill = Nodes)) +
  geom_boxplot()
```

```{r}
ggplot(prostate, aes(x = Acid, y = Age, color = Nodes)) +
  geom_jitter()
```


# Simple model with online linear term

```{r}
m_simple <- glm(Nodes ~ Acid, data = prostate, family = "binomial")
summary(m_simple)
```

```{r}
ggplot(prostate, aes(x = Acid, y = Nodes, color = Nodes)) +
  geom_jitter(height = 0.10) +
  stat_smooth(method="glm", color="green", se=FALSE,
              formula = Nodes ~ Acid,
              method.args = list(family="binomial"))
```

```{r}
prostate |>
  mutate(pred = predict(m_simple, type = "response")) |>
  ggplot() +
  geom_line(aes(x = Acid, y = pred))

```


# Simple model with quadratic term

```{r}
m_simple_quad <- glm(Nodes ~ Acid + I(Acid^2), data = prostate, family = "binomial")
summary(m_simple_quad)
```

```{r}
preds <- with(prostate, tibble(
  Acid = Acid, Nodes = predict(m_simple_quad, type = "response")))

ggplot(prostate) +
  geom_line(data = preds, aes(x = Acid, y = Nodes)) #+ 
  #geom_jitter(aes(x = Acid, y = as.numeric(Nodes), color = Nodes), height = 0.10)

```



# Multiple regression model

```{r}
m_multi <- glm(Nodes ~ Acid + Age, data = prostate, family = "binomial")
summary(m_multi)
```


```{r}
m_multi_interaction <- glm(Nodes ~ Acid*Age, data = prostate, family = "binomial")
summary(m_multi_interaction)
```


# Classification

```{r}
library(caret)

pred_test <- predict(m_simple, prostate, type="response")
class_test <- ifelse(pred_test >= 0.5, 0, 1)

conf_matrix <- confusionMatrix(as.factor(class_test),
                               as.factor(prostate$Nodes), positive = "1")
print(conf_matrix)


```

