{
  "hash": "64893470a38a82c0d8e676eb1cc27975",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple regression: the Japanese larches dataset\"\nformat: html\n---\n\n# Loading the dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\nneedles <- read.csv(\"needles.txt\", sep=\"\\t\")\nhead(needles)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  nitrogen phosphor potassium residu length\n1     2.20    0.417      1.35   1.79    351\n2     2.10    0.354      0.90   1.08    249\n3     1.52    0.208      0.71   0.47    171\n4     2.88    0.335      0.90   1.48    373\n5     2.18    0.314      1.26   1.09    321\n6     1.87    0.271      1.15   0.99    191\n```\n\n\n:::\n:::\n\n\nIf there are not too variables in the dataset (4-5 at most), it is often a good idea to make a pairwise scatterplot of the data. This will give you already some indication of (linear) relations between predictors and the outcome, or about any issues with multicollinearity (see later).\n\n\n::: {.cell}\n\n```{.r .cell-code}\npairs(needles)\n```\n\n::: {.cell-output-display}\n![](larches_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n# Forward model building\n\nThroughout this section and the following ones, we will use a significance level of $\\alpha = 0.10$. That means that we will add a term to our model if its p-value is below 10\\%.\n\n## Simple linear models\n\nWe first build a series of simple regression models, one for each predictor. We look for the model whose predictor is most significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- lm(length ~ nitrogen, data = needles)\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ nitrogen, data = needles)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-86.011 -42.385   3.295  26.201  98.621 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -151.14      51.08  -2.959  0.00684 ** \nnitrogen      183.42      26.31   6.971  3.3e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 56.04 on 24 degrees of freedom\nMultiple R-squared:  0.6694,\tAdjusted R-squared:  0.6556 \nF-statistic: 48.59 on 1 and 24 DF,  p-value: 3.298e-07\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- lm(length ~ phosphor, data = needles)\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ phosphor, data = needles)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-103.398  -42.582    2.331   40.845  120.220 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   -69.11      45.99  -1.503    0.146    \nphosphor     1060.29     177.08   5.988 3.51e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 61.71 on 24 degrees of freedom\nMultiple R-squared:  0.599,\tAdjusted R-squared:  0.5823 \nF-statistic: 35.85 on 1 and 24 DF,  p-value: 3.511e-06\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm3 <- lm(length ~ potassium, data = needles)\nsummary(m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ potassium, data = needles)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-123.572  -22.934   -2.391   28.872  134.441 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   -35.09      38.33  -0.915    0.369    \npotassium     304.05      47.91   6.346 1.46e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 59.55 on 24 degrees of freedom\nMultiple R-squared:  0.6266,\tAdjusted R-squared:  0.611 \nF-statistic: 40.27 on 1 and 24 DF,  p-value: 1.465e-06\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4 <- lm(length ~ residu, data = needles)\nsummary(m4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ residu, data = needles)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-90.74 -46.82 -14.47  41.63 125.26 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   -3.912     36.292  -0.108    0.915    \nresidu       225.952     38.502   5.869 4.71e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 62.45 on 24 degrees of freedom\nMultiple R-squared:  0.5893,\tAdjusted R-squared:  0.5722 \nF-statistic: 34.44 on 1 and 24 DF,  p-value: 4.711e-06\n```\n\n\n:::\n:::\n\n\nThe t-values for the predictors of model 1 through 4 are respectively 6.971, 5.988, 6.346, and 5.869. We choose the model with the largest absolute t-value (note that this corresponds to the smallest p-value), meaning that we choose model 1.\n\n## Adding one predictor\n\nWe now add one more predictor (of the three predictors that are left).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm12 <- lm(length ~ nitrogen + phosphor, data = needles)\nsummary(m12)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ nitrogen + phosphor, data = needles)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-57.834 -34.950  -0.539  20.364 127.287 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -189.64      42.53  -4.460 0.000179 ***\nnitrogen      123.83      26.62   4.652 0.000111 ***\nphosphor      604.44     162.65   3.716 0.001135 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 45.25 on 23 degrees of freedom\nMultiple R-squared:  0.7934,\tAdjusted R-squared:  0.7755 \nF-statistic: 44.17 on 2 and 23 DF,  p-value: 1.329e-08\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm13 <- lm(length ~ nitrogen + potassium, data = needles)\nsummary(m13)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ nitrogen + potassium, data = needles)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-75.625 -30.298   5.557  27.527  61.897 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -180.87      36.94  -4.896 6.04e-05 ***\nnitrogen      123.26      22.41   5.499 1.36e-05 ***\npotassium     188.69      38.40   4.913 5.79e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 39.98 on 23 degrees of freedom\nMultiple R-squared:  0.8387,\tAdjusted R-squared:  0.8247 \nF-statistic: 59.79 on 2 and 23 DF,  p-value: 7.727e-10\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm14 <- lm(length ~ nitrogen + residu, data = needles)\nsummary(m14)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ nitrogen + residu, data = needles)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-74.743 -34.276  -7.326  35.400  79.455 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -144.82      44.01  -3.291 0.003202 ** \nnitrogen      123.88      29.83   4.152 0.000385 ***\nresidu        120.07      39.17   3.065 0.005477 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 48.23 on 23 degrees of freedom\nMultiple R-squared:  0.7653,\tAdjusted R-squared:  0.7449 \nF-statistic:  37.5 on 2 and 23 DF,  p-value: 5.769e-08\n```\n\n\n:::\n:::\n\n\nThe next most significant term is potassium, so we choose `model13` that includes nitrogen and potassium.\n\n## Adding yet more predictors\n\nWe continue adding predictors. We start with the model that includes nitrogen and potassium and try to add more predictors, checking at each step whether the added predictor is significant.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm132 <- lm(length ~ nitrogen + potassium + phosphor, data = needles)\nsummary(m132)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ nitrogen + potassium + phosphor, data = needles)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-64.558 -32.031   6.262  27.049  85.526 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -193.07      35.78  -5.396 2.03e-05 ***\nnitrogen      107.80      22.92   4.702 0.000109 ***\npotassium     143.13      44.13   3.243 0.003731 ** \nphosphor      304.24     165.17   1.842 0.078998 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 38.05 on 22 degrees of freedom\nMultiple R-squared:  0.8602,\tAdjusted R-squared:  0.8412 \nF-statistic: 45.14 on 3 and 22 DF,  p-value: 1.435e-09\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm134 <- lm(length ~ nitrogen + potassium + residu, data = needles)\nsummary(m134)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ nitrogen + potassium + residu, data = needles)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-69.271 -26.878   3.609  21.446  70.267 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -172.99      36.39  -4.754 9.58e-05 ***\nnitrogen      106.50      24.57   4.335 0.000267 ***\npotassium     156.84      43.10   3.638 0.001450 ** \nresidu         54.28      36.45   1.489 0.150604    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 38.97 on 22 degrees of freedom\nMultiple R-squared:  0.8535,\tAdjusted R-squared:  0.8335 \nF-statistic: 42.71 on 3 and 22 DF,  p-value: 2.407e-09\n```\n\n\n:::\n:::\n\n\nThe `residu` predictor is not significant, but `phosphor` is, so we select model `m132`. \n\n## Wrapping up\n\nAs a last step, we build one more model: we try to add `residu` to `m132`. This term is not significant, so we don't include it. *Our final model is m132`*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1324 <- lm(length ~ nitrogen + potassium + phosphor + residu, data = needles)\nsummary(m1324)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ nitrogen + potassium + phosphor + residu, \n    data = needles)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-61.56 -29.11  10.28  24.72  80.29 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -185.33      36.30  -5.106 4.67e-05 ***\nnitrogen       97.76      24.57   3.979 0.000684 ***\npotassium     126.57      46.43   2.726 0.012653 *  \nphosphor      256.97     169.91   1.512 0.145321    \nresidu         40.28      36.61   1.100 0.283773    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 37.87 on 21 degrees of freedom\nMultiple R-squared:  0.8679,\tAdjusted R-squared:  0.8427 \nF-statistic: 34.48 on 4 and 21 DF,  p-value: 5.967e-09\n```\n\n\n:::\n:::\n\n\n# Automating the model building procedure\n\nWe had to build no less than 10 models before settling on the final one. Luckily R contains automated model building functions, using the `step` function. This function can build a model using the forward or backward procedure. Here we use it for forward model building: `step` will repeatedly try to add predictors to the model, until it reaches the full model (the model with all predictors included). At each step, the function computes the so-called AIC (Akaike Information Coefficient) of the model, a measure for the complexity of the model that we will encounter later in the course. Models with lower AIC are generally simpler and better able to explain the data (but this is only a rule-of-thumb).\n \n\n::: {.cell}\n\n```{.r .cell-code}\nempty <- lm(length ~ 1, data = needles)  # a model with only an intercept\nfull <- lm(length ~ ., data = needles)  # a model with all predictors\n\nmodel_forward <- step(\n  empty,\n  scope = list(lower = empty, upper = full),\n  direction = \"forward\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nStart:  AIC=238.05\nlength ~ 1\n\n            Df Sum of Sq    RSS    AIC\n+ nitrogen   1    152591  75363 211.27\n+ potassium  1    142832  85123 214.44\n+ phosphor   1    136550  91404 216.29\n+ residu     1    134340  93614 216.91\n<none>                   227954 238.05\n\nStep:  AIC=211.27\nlength ~ nitrogen\n\n            Df Sum of Sq   RSS    AIC\n+ potassium  1     38593 36771 194.61\n+ phosphor   1     28274 47090 201.04\n+ residu     1     21860 53503 204.36\n<none>                   75363 211.27\n\nStep:  AIC=194.61\nlength ~ nitrogen + potassium\n\n           Df Sum of Sq   RSS    AIC\n+ phosphor  1    4913.2 31858 192.88\n+ residu    1    3367.7 33403 194.12\n<none>                  36771 194.61\n\nStep:  AIC=192.88\nlength ~ nitrogen + potassium + phosphor\n\n         Df Sum of Sq   RSS    AIC\n<none>                31858 192.88\n+ residu  1    1735.7 30122 193.43\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_forward)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ nitrogen + potassium + phosphor, data = needles)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-64.558 -32.031   6.262  27.049  85.526 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  -193.07      35.78  -5.396 2.03e-05 ***\nnitrogen      107.80      22.92   4.702 0.000109 ***\npotassium     143.13      44.13   3.243 0.003731 ** \nphosphor      304.24     165.17   1.842 0.078998 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 38.05 on 22 degrees of freedom\nMultiple R-squared:  0.8602,\tAdjusted R-squared:  0.8412 \nF-statistic: 45.14 on 3 and 22 DF,  p-value: 1.435e-09\n```\n\n\n:::\n:::\n\n\nLooking at the final model, we see that we get the exact same model as with our earlier, manual model building procedure. This is not guaranteed; different model building procedures may result in different models.\n\n## Interaction terms\n\nLastly, we add two interaction terms to our model, to incorporate interactions between `residu` and `phosphor` on the one hand, and `phosphor` and `nitrogen` on the other. As discussed in the theory lecture, you would typically add these interaction terms because you think (on biological or physical grounds) that they should be there. You wouldn't perform an exhaustive search across all interaction terms.\n\nIf we add an interaction term, then the individual variables should also be present. We can achieve that in two ways: first, by using the `*` syntax:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_interaction <- lm(length ~ potassium + residu * phosphor + phosphor * nitrogen, data = needles)\nsummary(model_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ potassium + residu * phosphor + phosphor * \n    nitrogen, data = needles)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-57.559 -18.976   0.007  11.608  55.941 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)   \n(Intercept)         129.09     169.33   0.762   0.4552   \npotassium           137.97      41.24   3.346   0.0034 **\nresidu              193.80      89.10   2.175   0.0425 * \nphosphor          -1000.02     682.98  -1.464   0.1595   \nnitrogen           -150.76      97.08  -1.553   0.1369   \nresidu:phosphor    -598.08     290.02  -2.062   0.0531 . \nphosphor:nitrogen   951.78     371.57   2.562   0.0191 * \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 33.43 on 19 degrees of freedom\nMultiple R-squared:  0.9069,\tAdjusted R-squared:  0.8774 \nF-statistic: 30.83 on 6 and 19 DF,  p-value: 8.159e-09\n```\n\n\n:::\n:::\n\n\nSecondly, you can specify all terms explicitly. Note that the resulting models are the same.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_interaction <- lm(length ~ potassium + residu + phosphor + nitrogen + \n                                 residu : phosphor + phosphor : nitrogen, data = needles)\nsummary(model_interaction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = length ~ potassium + residu + phosphor + nitrogen + \n    residu:phosphor + phosphor:nitrogen, data = needles)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-57.559 -18.976   0.007  11.608  55.941 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)   \n(Intercept)         129.09     169.33   0.762   0.4552   \npotassium           137.97      41.24   3.346   0.0034 **\nresidu              193.80      89.10   2.175   0.0425 * \nphosphor          -1000.02     682.98  -1.464   0.1595   \nnitrogen           -150.76      97.08  -1.553   0.1369   \nresidu:phosphor    -598.08     290.02  -2.062   0.0531 . \nphosphor:nitrogen   951.78     371.57   2.562   0.0191 * \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 33.43 on 19 degrees of freedom\nMultiple R-squared:  0.9069,\tAdjusted R-squared:  0.8774 \nF-statistic: 30.83 on 6 and 19 DF,  p-value: 8.159e-09\n```\n\n\n:::\n:::\n\n\nNote that we keep `phosphor` and `nitrogen` in the model even though they are individually non-significant. As long as there is an interaction term involving a variable, that variable stays in the model.\n\n# Diagnostic plots\n\nOnce you have built a model, don't forget to check the diagnostic plots and adjust the model as needed. Judging from the diagnostic plots, our model (with interaction terms) is fine and doesn't require any adjustments at this stage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(model_interaction)\n```\n\n::: {.cell-output-display}\n![](larches_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n",
    "supporting": [
      "larches_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}