<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Multiple regression: the Japanese larches dataset</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-12acf3a2dea5fb6071b1261511aaf884.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Multiple regression: the Japanese larches dataset</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="loading-the-dataset" class="level1">
<h1>Loading the dataset</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>needles <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"needles.txt"</span>, <span class="at">sep=</span><span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(needles)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  nitrogen phosphor potassium residu length
1     2.20    0.417      1.35   1.79    351
2     2.10    0.354      0.90   1.08    249
3     1.52    0.208      0.71   0.47    171
4     2.88    0.335      0.90   1.48    373
5     2.18    0.314      1.26   1.09    321
6     1.87    0.271      1.15   0.99    191</code></pre>
</div>
</div>
<p>If there are not too variables in the dataset (4-5 at most), it is often a good idea to make a pairwise scatterplot of the data. This will give you already some indication of (linear) relations between predictors and the outcome, or about any issues with multicollinearity (see later).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(needles)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="larches_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="forward-model-building" class="level1">
<h1>Forward model building</h1>
<p>Throughout this section and the following ones, we will use a significance level of <span class="math inline">\(\alpha = 0.10\)</span>. That means that we will add a term to our model if its p-value is below 10%.</p>
<section id="simple-linear-models" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-models">Simple linear models</h2>
<p>We first build a series of simple regression models, one for each predictor. We look for the model whose predictor is most significant.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> nitrogen, <span class="at">data =</span> needles)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ nitrogen, data = needles)

Residuals:
    Min      1Q  Median      3Q     Max 
-86.011 -42.385   3.295  26.201  98.621 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -151.14      51.08  -2.959  0.00684 ** 
nitrogen      183.42      26.31   6.971  3.3e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 56.04 on 24 degrees of freedom
Multiple R-squared:  0.6694,    Adjusted R-squared:  0.6556 
F-statistic: 48.59 on 1 and 24 DF,  p-value: 3.298e-07</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> phosphor, <span class="at">data =</span> needles)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ phosphor, data = needles)

Residuals:
     Min       1Q   Median       3Q      Max 
-103.398  -42.582    2.331   40.845  120.220 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -69.11      45.99  -1.503    0.146    
phosphor     1060.29     177.08   5.988 3.51e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 61.71 on 24 degrees of freedom
Multiple R-squared:  0.599, Adjusted R-squared:  0.5823 
F-statistic: 35.85 on 1 and 24 DF,  p-value: 3.511e-06</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> potassium, <span class="at">data =</span> needles)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ potassium, data = needles)

Residuals:
     Min       1Q   Median       3Q      Max 
-123.572  -22.934   -2.391   28.872  134.441 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -35.09      38.33  -0.915    0.369    
potassium     304.05      47.91   6.346 1.46e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 59.55 on 24 degrees of freedom
Multiple R-squared:  0.6266,    Adjusted R-squared:  0.611 
F-statistic: 40.27 on 1 and 24 DF,  p-value: 1.465e-06</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>m4 <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> residu, <span class="at">data =</span> needles)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m4)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ residu, data = needles)

Residuals:
   Min     1Q Median     3Q    Max 
-90.74 -46.82 -14.47  41.63 125.26 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   -3.912     36.292  -0.108    0.915    
residu       225.952     38.502   5.869 4.71e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 62.45 on 24 degrees of freedom
Multiple R-squared:  0.5893,    Adjusted R-squared:  0.5722 
F-statistic: 34.44 on 1 and 24 DF,  p-value: 4.711e-06</code></pre>
</div>
</div>
<p>The t-values for the predictors of model 1 through 4 are respectively 6.971, 5.988, 6.346, and 5.869. We choose the model with the largest absolute t-value (note that this corresponds to the smallest p-value), meaning that we choose model 1.</p>
</section>
<section id="adding-one-predictor" class="level2">
<h2 class="anchored" data-anchor-id="adding-one-predictor">Adding one predictor</h2>
<p>We now add one more predictor (of the three predictors that are left).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>m12 <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> nitrogen <span class="sc">+</span> phosphor, <span class="at">data =</span> needles)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m12)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ nitrogen + phosphor, data = needles)

Residuals:
    Min      1Q  Median      3Q     Max 
-57.834 -34.950  -0.539  20.364 127.287 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -189.64      42.53  -4.460 0.000179 ***
nitrogen      123.83      26.62   4.652 0.000111 ***
phosphor      604.44     162.65   3.716 0.001135 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 45.25 on 23 degrees of freedom
Multiple R-squared:  0.7934,    Adjusted R-squared:  0.7755 
F-statistic: 44.17 on 2 and 23 DF,  p-value: 1.329e-08</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>m13 <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> nitrogen <span class="sc">+</span> potassium, <span class="at">data =</span> needles)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m13)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ nitrogen + potassium, data = needles)

Residuals:
    Min      1Q  Median      3Q     Max 
-75.625 -30.298   5.557  27.527  61.897 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -180.87      36.94  -4.896 6.04e-05 ***
nitrogen      123.26      22.41   5.499 1.36e-05 ***
potassium     188.69      38.40   4.913 5.79e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 39.98 on 23 degrees of freedom
Multiple R-squared:  0.8387,    Adjusted R-squared:  0.8247 
F-statistic: 59.79 on 2 and 23 DF,  p-value: 7.727e-10</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>m14 <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> nitrogen <span class="sc">+</span> residu, <span class="at">data =</span> needles)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m14)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ nitrogen + residu, data = needles)

Residuals:
    Min      1Q  Median      3Q     Max 
-74.743 -34.276  -7.326  35.400  79.455 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -144.82      44.01  -3.291 0.003202 ** 
nitrogen      123.88      29.83   4.152 0.000385 ***
residu        120.07      39.17   3.065 0.005477 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 48.23 on 23 degrees of freedom
Multiple R-squared:  0.7653,    Adjusted R-squared:  0.7449 
F-statistic:  37.5 on 2 and 23 DF,  p-value: 5.769e-08</code></pre>
</div>
</div>
<p>The next most significant term is potassium, so we choose <code>model13</code> that includes nitrogen and potassium.</p>
</section>
<section id="adding-yet-more-predictors" class="level2">
<h2 class="anchored" data-anchor-id="adding-yet-more-predictors">Adding yet more predictors</h2>
<p>We continue adding predictors. We start with the model that includes nitrogen and potassium and try to add more predictors, checking at each step whether the added predictor is significant.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>m132 <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> nitrogen <span class="sc">+</span> potassium <span class="sc">+</span> phosphor, <span class="at">data =</span> needles)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m132)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ nitrogen + potassium + phosphor, data = needles)

Residuals:
    Min      1Q  Median      3Q     Max 
-64.558 -32.031   6.262  27.049  85.526 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -193.07      35.78  -5.396 2.03e-05 ***
nitrogen      107.80      22.92   4.702 0.000109 ***
potassium     143.13      44.13   3.243 0.003731 ** 
phosphor      304.24     165.17   1.842 0.078998 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 38.05 on 22 degrees of freedom
Multiple R-squared:  0.8602,    Adjusted R-squared:  0.8412 
F-statistic: 45.14 on 3 and 22 DF,  p-value: 1.435e-09</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>m134 <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> nitrogen <span class="sc">+</span> potassium <span class="sc">+</span> residu, <span class="at">data =</span> needles)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m134)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ nitrogen + potassium + residu, data = needles)

Residuals:
    Min      1Q  Median      3Q     Max 
-69.271 -26.878   3.609  21.446  70.267 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -172.99      36.39  -4.754 9.58e-05 ***
nitrogen      106.50      24.57   4.335 0.000267 ***
potassium     156.84      43.10   3.638 0.001450 ** 
residu         54.28      36.45   1.489 0.150604    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 38.97 on 22 degrees of freedom
Multiple R-squared:  0.8535,    Adjusted R-squared:  0.8335 
F-statistic: 42.71 on 3 and 22 DF,  p-value: 2.407e-09</code></pre>
</div>
</div>
<p>The <code>residu</code> predictor is not significant, but <code>phosphor</code> is, so we select model <code>m132</code>.</p>
</section>
<section id="wrapping-up" class="level2">
<h2 class="anchored" data-anchor-id="wrapping-up">Wrapping up</h2>
<p>As a last step, we build one more model: we try to add <code>residu</code> to <code>m132</code>. This term is not significant, so we don’t include it. <em>Our final model is m132`</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>m1324 <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> nitrogen <span class="sc">+</span> potassium <span class="sc">+</span> phosphor <span class="sc">+</span> residu, <span class="at">data =</span> needles)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1324)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ nitrogen + potassium + phosphor + residu, 
    data = needles)

Residuals:
   Min     1Q Median     3Q    Max 
-61.56 -29.11  10.28  24.72  80.29 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -185.33      36.30  -5.106 4.67e-05 ***
nitrogen       97.76      24.57   3.979 0.000684 ***
potassium     126.57      46.43   2.726 0.012653 *  
phosphor      256.97     169.91   1.512 0.145321    
residu         40.28      36.61   1.100 0.283773    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 37.87 on 21 degrees of freedom
Multiple R-squared:  0.8679,    Adjusted R-squared:  0.8427 
F-statistic: 34.48 on 4 and 21 DF,  p-value: 5.967e-09</code></pre>
</div>
</div>
</section>
</section>
<section id="automating-the-model-building-procedure" class="level1">
<h1>Automating the model building procedure</h1>
<p>We had to build no less than 10 models before settling on the final one. Luckily R contains automated model building functions, using the <code>step</code> function. This function can build a model using the forward or backward procedure. Here we use it for forward model building: <code>step</code> will repeatedly try to add predictors to the model, until it reaches the full model (the model with all predictors included). At each step, the function computes the so-called AIC (Akaike Information Coefficient) of the model, a measure for the complexity of the model that we will encounter later in the course. Models with lower AIC are generally simpler and better able to explain the data (but this is only a rule-of-thumb).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>empty <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> needles)  <span class="co"># a model with only an intercept</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>full <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> ., <span class="at">data =</span> needles)  <span class="co"># a model with all predictors</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>model_forward <span class="ot">&lt;-</span> <span class="fu">step</span>(</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  empty,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> empty, <span class="at">upper =</span> full),</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">direction =</span> <span class="st">"forward"</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=238.05
length ~ 1

            Df Sum of Sq    RSS    AIC
+ nitrogen   1    152591  75363 211.27
+ potassium  1    142832  85123 214.44
+ phosphor   1    136550  91404 216.29
+ residu     1    134340  93614 216.91
&lt;none&gt;                   227954 238.05

Step:  AIC=211.27
length ~ nitrogen

            Df Sum of Sq   RSS    AIC
+ potassium  1     38593 36771 194.61
+ phosphor   1     28274 47090 201.04
+ residu     1     21860 53503 204.36
&lt;none&gt;                   75363 211.27

Step:  AIC=194.61
length ~ nitrogen + potassium

           Df Sum of Sq   RSS    AIC
+ phosphor  1    4913.2 31858 192.88
+ residu    1    3367.7 33403 194.12
&lt;none&gt;                  36771 194.61

Step:  AIC=192.88
length ~ nitrogen + potassium + phosphor

         Df Sum of Sq   RSS    AIC
&lt;none&gt;                31858 192.88
+ residu  1    1735.7 30122 193.43</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_forward)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ nitrogen + potassium + phosphor, data = needles)

Residuals:
    Min      1Q  Median      3Q     Max 
-64.558 -32.031   6.262  27.049  85.526 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  -193.07      35.78  -5.396 2.03e-05 ***
nitrogen      107.80      22.92   4.702 0.000109 ***
potassium     143.13      44.13   3.243 0.003731 ** 
phosphor      304.24     165.17   1.842 0.078998 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 38.05 on 22 degrees of freedom
Multiple R-squared:  0.8602,    Adjusted R-squared:  0.8412 
F-statistic: 45.14 on 3 and 22 DF,  p-value: 1.435e-09</code></pre>
</div>
</div>
<p>Looking at the final model, we see that we get the exact same model as with our earlier, manual model building procedure. This is not guaranteed; different model building procedures may result in different models.</p>
<section id="interaction-terms" class="level2">
<h2 class="anchored" data-anchor-id="interaction-terms">Interaction terms</h2>
<p>Lastly, we add two interaction terms to our model, to incorporate interactions between <code>residu</code> and <code>phosphor</code> on the one hand, and <code>phosphor</code> and <code>nitrogen</code> on the other. As discussed in the theory lecture, you would typically add these interaction terms because you think (on biological or physical grounds) that they should be there. You wouldn’t perform an exhaustive search across all interaction terms.</p>
<p>If we add an interaction term, then the individual variables should also be present. We can achieve that in two ways: first, by using the <code>*</code> syntax:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>model_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> potassium <span class="sc">+</span> residu <span class="sc">*</span> phosphor <span class="sc">+</span> phosphor <span class="sc">*</span> nitrogen, <span class="at">data =</span> needles)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_interaction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ potassium + residu * phosphor + phosphor * 
    nitrogen, data = needles)

Residuals:
    Min      1Q  Median      3Q     Max 
-57.559 -18.976   0.007  11.608  55.941 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)         129.09     169.33   0.762   0.4552   
potassium           137.97      41.24   3.346   0.0034 **
residu              193.80      89.10   2.175   0.0425 * 
phosphor          -1000.02     682.98  -1.464   0.1595   
nitrogen           -150.76      97.08  -1.553   0.1369   
residu:phosphor    -598.08     290.02  -2.062   0.0531 . 
phosphor:nitrogen   951.78     371.57   2.562   0.0191 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 33.43 on 19 degrees of freedom
Multiple R-squared:  0.9069,    Adjusted R-squared:  0.8774 
F-statistic: 30.83 on 6 and 19 DF,  p-value: 8.159e-09</code></pre>
</div>
</div>
<p>Secondly, you can specify all terms explicitly. Note that the resulting models are the same.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>model_interaction <span class="ot">&lt;-</span> <span class="fu">lm</span>(length <span class="sc">~</span> potassium <span class="sc">+</span> residu <span class="sc">+</span> phosphor <span class="sc">+</span> nitrogen <span class="sc">+</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                                 residu <span class="sc">:</span> phosphor <span class="sc">+</span> phosphor <span class="sc">:</span> nitrogen, <span class="at">data =</span> needles)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_interaction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = length ~ potassium + residu + phosphor + nitrogen + 
    residu:phosphor + phosphor:nitrogen, data = needles)

Residuals:
    Min      1Q  Median      3Q     Max 
-57.559 -18.976   0.007  11.608  55.941 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)         129.09     169.33   0.762   0.4552   
potassium           137.97      41.24   3.346   0.0034 **
residu              193.80      89.10   2.175   0.0425 * 
phosphor          -1000.02     682.98  -1.464   0.1595   
nitrogen           -150.76      97.08  -1.553   0.1369   
residu:phosphor    -598.08     290.02  -2.062   0.0531 . 
phosphor:nitrogen   951.78     371.57   2.562   0.0191 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 33.43 on 19 degrees of freedom
Multiple R-squared:  0.9069,    Adjusted R-squared:  0.8774 
F-statistic: 30.83 on 6 and 19 DF,  p-value: 8.159e-09</code></pre>
</div>
</div>
<p>Note that we keep <code>phosphor</code> and <code>nitrogen</code> in the model even though they are individually non-significant. As long as there is an interaction term involving a variable, that variable stays in the model.</p>
</section>
</section>
<section id="diagnostic-plots" class="level1">
<h1>Diagnostic plots</h1>
<p>Once you have built a model, don’t forget to check the diagnostic plots and adjust the model as needed. Judging from the diagnostic plots, our model (with interaction terms) is fine and doesn’t require any adjustments at this stage.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_interaction)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="larches_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/ugent-korea\.github\.io\/ISM-slides\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>