{
  "hash": "467a214bcfc723e7b416e91bcaeb6144",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Chapter 1: Linear regression\"\nsubtitle: \"Introduction\"\nauthor: \"Joris Vankerschaver\"\nheader-includes:\n  - \\useinnertheme[shadow=true]{rounded}\n  - \\usecolortheme{rose}\n  - \\setbeamertemplate{footline}[frame number]\n  - \\usepackage{color}\n  - \\usepackage{graphicx}\noutput: \n  beamer_presentation:\n    theme: \"default\"\n    keep_tex: true\n    includes:\n      in_header: columns.tex\n---\n\n\n\n\n## Problem setting\n\n- 26 observations from class of 2021-22 (19 female and 7 male) + 1 professor (**27 total**)\n- Measurement of right \\alert{palm width} and \\alert{height} (both in cm).\n- Random sample? From which population?\n- Sources of bias, error?\n\n\\begin{block}{Research questions}\n\\begin{enumerate}\n\\item Is there an association between height and palm width?\n\\item Can we predict a person's height from their palm width?\n\\item If yes, how confident are we in these results?\n\\end{enumerate}\n\\end{block}\n\n## Simple and multiple linear regression\n\n- In this lecture, we build a **simple linear regression** model.\n- Simple regression: effect on height of a single predictor (palm width)\n- Multiple regression: multiple predictors (palm width, gender, year, ...)\n\n## The raw data\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01_Regression-0_files/figure-html/unnamed-chunk-2-1.png){width=576}\n:::\n:::\n\n\n## Associating height with palm width\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01_Regression-0_files/figure-html/unnamed-chunk-3-1.png){width=576}\n:::\n:::\n\n\n## Via R\n\n\\footnotesize\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Height ~ Palm.width, data = heights)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-17.7055  -3.1967  -0.2853   3.1882  10.3919 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   87.450     10.814   8.087 1.93e-08 ***\nPalm.width     9.911      1.338   7.408 9.26e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.459 on 25 degrees of freedom\nMultiple R-squared:  0.687,\tAdjusted R-squared:  0.6745 \nF-statistic: 54.88 on 1 and 25 DF,  p-value: 9.264e-08\n```\n\n\n:::\n:::\n\n\\normalsize\n\n## Model diagnostics\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01_Regression-0_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n## Predicting height from palm width\n\n- Model: $E(H|W = w) = 87.45 + 9.91 \\times w$. \n\n- Predicted expected height of a person with palm width 8.75cm:\n$$\n  E(H|W = 8.75) = 87.45 + 9.91 \\times 8.75 =  174.17 \\,\\text{cm}\n$$\n\nRegression coefficients:\n\n- **Intercept** (87.45cm): height of a hypothetical student with palms that are 0 cm wide. Often makes more sense after mean-centering.\n- **Slope** (9.91): each extra cm in palm width is associated with an increase of 9.91 cm in height.\n\n\n## Be careful with extrapolating\n\nPredicting outside the range of the data can yield misleading results.\n\n![](./images/01-linear-regression/xkcd-605.png)\n\n[Source: XKCD](https://xkcd.com/605/)\n\n## What is the uncertainty in our prediction?\n\nAssuming that our model is good, how accurate are the predictions from it?\n\nFor prediction $E(H|W = 8.75) =  174.17 \\,\\text{cm}$:\n\n- 95% confidence interval: $[171.27, 177.08]$. Uncertainty in **average prediction**.\n- 95% prediction interval: $[162.56, 185.79]$. Uncertainty in **individual predictions**.\n\n## What is the uncertainty in our prediction?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](01_Regression-0_files/figure-html/unnamed-chunk-6-1.png){width=576}\n:::\n:::\n\n\n## Association between predictor and outcome\n\nThe regression slope $\\beta = 9.91$ measures the strength of the  association between palm width and height.\n\n- If close to 0: no association\n- If different from 0: some degree of association\n\nHow do we test whether $\\beta$ is 0? \n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(m)$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Estimate Std. Error  t value     Pr(>|t|)\n(Intercept) 87.449557  10.813838 8.086819 1.928912e-08\nPalm.width   9.911427   1.337903 7.408178 9.263523e-08\n```\n\n\n:::\n:::\n",
    "supporting": [
      "01_Regression-0_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}